### ISSUE TITLE
Example does not build with cargo-1.59.0

### ISSUE THREAD

**Issue by UweBonnes** [ololoshka2871/stm32l442-usb-example#1]
>zypper in cargo1.59
...
>cargo build
...
   Compiling quote v1.0.27
error[E0463]: can't find crate for `core`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed
  = help: consider downloading the target with `rustup target add thumbv7em-none-eabihf`

error[E0463]: can't find crate for `compiler_builtins`
...

**Comment by ololoshka2871** [comment]
> = help: consider downloading the target with rustup target add thumbv7em-none-eabihf
You need to install rust toolchain for cortex-m4 `thumbv7em-none-eabihf`, so run the command
`rustup target add thumbv7em-none-eabihf`
